# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'localization_ak' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftGen', '~> 6.0'
  # Pods for localization_ak

end
